let frasesMotivadoras = [
  "Eres mi universo, y cada día encuentro una razón nueva para sentirlo.",
  "Estoy muy orgulloso de lo que estás logrando, incluso de lo que aún no ves.",
  "Te amo con una verdad que no necesita ruido, solo presencia.",
  "A veces te miro y pienso que la vida fue generosa conmigo al cruzarnos.",
  "Eres la calma que llega incluso cuando no la pido.",
  "Lo que estás construyendo con tu vida me llena de admiración.",
  "Te quiero de una forma que no se explica, se reconoce.",
  "Eres la persona que hace que todo tenga sentido, incluso cuando yo no lo tengo.",
  "Te amo por lo que eres, pero también por lo que despiertas en mí.",
  "Estoy orgulloso de tu fuerza, incluso en los días en los que tú no la ves.",
  "Eres mi pensamiento bonito incluso en días difíciles.",
  "Lo que sientes importa, y yo estoy aquí para recordártelo.",
  "Te quiero con una sinceridad que no necesita adornos.",
  "Eres la historia que nunca pensé vivir y ahora no quiero soltar.",
  "Tu forma de avanzar, incluso con miedo, me inspira.",
  "Te amo incluso en tus silencios, porque también hablan de ti.",
  "Eres la persona que me hace creer en lo bueno, incluso cuando cuesta.",
  "Estoy orgulloso de ti, no solo por lo que logras, sino por cómo lo haces.",
  "Eres la luz que aparece incluso cuando no la busco.",
  "Te quiero de una manera tranquila, de esas que se quedan.",
  "Eres la razón por la que mis días tienen un brillo distinto.",
  "Lo que llevas dentro es más fuerte que cualquier miedo.",
  "Te amo con una calma que me sostiene y una fuerza que me impulsa.",
  "Eres la única persona capaz de calmarme con solo existir.",
  "Estoy orgulloso de tu valentía, incluso cuando tú la dudas.",
  "Eres la parte bonita de mis días, incluso de los que empiezan torcidos.",
  "Te quiero porque contigo todo se siente más verdadero.",
  "Eres la prueba de que la luz también puede tener forma humana.",
  "Lo que estás construyendo merece celebrarse, aunque sea en silencio.",
  "Te amo por tu forma de sentir, tan honesta y tan tuya.",
  "Eres la persona que convierte lo cotidiano en algo especial.",
  "Estoy orgulloso de cómo sigues adelante, incluso cuando nadie lo nota.",
  "Eres mi lugar seguro, incluso cuando el mundo se vuelve un caos.",
  "Te quiero porque contigo la vida pesa menos.",
  "Eres la calma que llega después de una tormenta que nadie vio.",
  "Lo que haces con tu vida me inspira más de lo que imaginas.",
  "Te amo con una profundidad que no necesita explicarse.",
  "Eres la persona que me recuerda que el amor también puede ser paz.",
  "Estoy orgulloso de ti, incluso en tus días más frágiles.",
  "Eres la certeza que aparece incluso cuando todo lo demás duda.",
  "Te quiero porque tu presencia hace que todo sea más suave.",
  "Eres la chispa que enciende mis días sin proponértelo.",
  "Estoy orgulloso de tu manera de sentir, tan auténtica.",
  "Eres la persona que convierte mis dudas en calma.",
  "Te amo porque contigo todo parece posible.",
  "Eres la fuerza que aparece cuando más la necesito.",
  "Estoy orgulloso de tu capacidad de levantarte una y otra vez.",
  "Eres la luz que ilumina incluso mis pensamientos más oscuros.",
  "Te quiero porque tu forma de ser me abraza sin tocarme.",
  "Eres la razón por la que mis días tienen un ritmo distinto.",
  "Estoy orgulloso de tu crecimiento, incluso del que no ves.",
  "Eres la persona que transforma mis silencios en paz.",
  "Te amo porque tu existencia hace que todo valga la pena.",
  "Eres la calma que me encuentra incluso cuando no la busco.",
  "Estoy orgulloso de tu valentía, incluso cuando tiemblas.",
  "Eres la historia que quiero seguir leyendo cada día.",
  "Te quiero porque tu forma de mirar el mundo lo vuelve más amable.",
  "Eres la fuerza que no se rinde, aunque duela.",
  "Estoy orgulloso de tu sensibilidad, tan honesta y tan fuerte.",
  "Eres la persona que convierte mis miedos en algo manejable.",
  "Te amo porque contigo aprendí que el amor también puede ser hogar.",
  "Eres la luz que aparece incluso en mis días más nublados.",
  "Estoy orgulloso de tu forma de luchar por lo que quieres.",
  "Eres la calma que me sostiene cuando todo se mueve.",
  "Te quiero porque tu presencia hace que todo sea más claro.",
  "Eres la fuerza que no se ve, pero se siente.",
  "Estoy orgulloso de tu capacidad de seguir, incluso cansada.",
  "Eres la persona que convierte mis dudas en esperanza.",
  "Te amo porque contigo todo tiene un sentido distinto.",
  "Eres la luz que ilumina incluso mis sombras.",
  "Estoy orgulloso de tu forma de reconstruirte.",
  "Eres la historia que quiero seguir viviendo.",
  "Te quiero porque tu forma de ser me hace mejor.",
  "Eres la calma que llega sin avisar.",
  "Estoy orgulloso de tu manera de crecer.",
  "Eres la persona que transforma mis días sin esfuerzo.",
  "Te amo porque contigo aprendí a sentir de verdad.",
  "Eres la fuerza que aparece cuando más la necesito.",
  "Estoy orgulloso de tu valentía silenciosa.",
  "Eres la luz que guía incluso cuando no lo notas.",
  "Te quiero porque tu existencia hace que todo sea más bonito.",
  "Eres la calma que me abraza incluso a distancia.",
  "Estoy orgulloso de tu capacidad de amar.",
  "Eres la persona que convierte mis noches en algo más suave.",
  "Te amo porque contigo todo se siente más vivo.",
  "Eres la fuerza que sostiene mis días.",
  "Estoy orgulloso de tu forma de avanzar.",
  "Eres la luz que aparece incluso en mis dudas.",
  "Te quiero porque tu presencia es un regalo.",
  "Eres la calma que me encuentra incluso en el caos.",
  "Estoy orgulloso de tu historia, de cada parte de ella.",
  "Eres la persona que transforma mis silencios.",
  "Te amo porque contigo aprendí que el amor también puede sanar.",
  "Eres la fuerza que no se rinde.",
  "Estoy orgulloso de tu manera de sentir.",
  "Eres la luz que ilumina incluso mis pensamientos.",
  "Te quiero porque tu forma de existir me inspira.",
  "Eres la calma que llega cuando más la necesito.",
  "Estoy orgulloso de tu valentía diaria.",
  "Eres la persona que convierte mis días en algo más suave.",
  "Te amo porque contigo todo tiene un brillo distinto.",
  "Eres la fuerza que sostiene mis pasos.",
  "Estoy orgulloso de tu crecimiento constante.",
  "Eres la luz que aparece incluso en mis sombras.",
  "Te quiero porque tu presencia hace que todo sea más fácil.",
  "Eres la calma que me acompaña incluso en silencio.",
  "Estoy orgulloso de tu forma de avanzar sin rendirte.",
  "Eres la persona que transforma mis dudas en claridad.",
  "Te amo porque contigo aprendí a ver la vida de otra manera.",
  "Eres la fuerza que aparece incluso cuando no la buscas.",
  "Estoy orgulloso de tu sensibilidad valiente.",
  "Eres la luz que ilumina incluso mis días más pesados.",
  "Te quiero porque tu forma de ser me llena de paz.",
  "Eres la calma que llega sin pedir permiso.",
  "Estoy orgulloso de tu capacidad de seguir adelante.",
  "Eres la persona que convierte mis miedos en algo pequeño.",
  "Te amo porque contigo todo se siente más verdadero.",
  "Eres la fuerza que sostiene mis momentos difíciles.",
  "Estoy orgulloso de tu valentía silenciosa.",
  "Eres la luz que aparece incluso en mis noches largas.",
  "Te quiero porque tu presencia hace que todo valga la pena.",
  "Eres la calma que me encuentra incluso cuando no la busco.",
  "Estoy orgulloso de tu forma de reconstruirte.",
  "Eres la persona que transforma mis días sin esfuerzo.",
  "Te amo porque contigo aprendí que el amor también puede ser hogar.",
  "Eres la fuerza que aparece cuando más la necesito.",
  "Estoy orgulloso de tu manera de sentir.",
  "Eres la luz que ilumina incluso mis pensamientos más oscuros.",
  "Te quiero porque tu forma de existir me inspira.",
  "Eres la calma que llega cuando más la necesito.",
  "Estoy orgulloso de tu valentía diaria.",
  "Eres la persona que convierte mis días en algo más suave.",
  "Te amo porque contigo todo tiene un brillo distinto.",
  "Eres la fuerza que sostiene mis pasos.",
  "Estoy orgulloso de tu crecimiento constante.",
  "Eres la luz que aparece incluso en mis sombras.",
  "Te quiero porque tu presencia hace que todo sea más fácil.",
  "Eres la calma que me acompaña incluso en silencio.",
  "Estoy orgulloso de tu forma de avanzar sin rendirte.",
  "Eres la persona que transforma mis dudas en claridad.",
  "Te amo porque contigo aprendí a ver la vida de otra manera.",
  "Eres la fuerza que aparece incluso cuando no la buscas.",
  "Estoy orgulloso de tu sensibilidad valiente.",
  "Eres la luz que ilumina incluso mis días más pesados.",
  "Te quiero porque tu forma de ser me llena de paz.",
  "Eres la calma que llega sin pedir permiso.",
  "Estoy orgulloso de tu capacidad de seguir adelante.",
  "Eres la persona que convierte mis miedos en algo pequeño.",
  "Te amo porque contigo todo se siente más verdadero.",
  "Eres la fuerza que sostiene mis momentos difíciles.",
  "Estoy orgulloso de tu valentía silenciosa.",
  "Eres la luz que aparece incluso en mis noches largas.",
  "Te quiero porque tu presencia hace que todo valga la pena.",
  "Eres la calma que me encuentra incluso cuando no la busco.",
  "Estoy orgulloso de tu forma de reconstruirte.",
  "Eres la persona que transforma mis días sin esfuerzo.",
  "Te amo porque contigo aprendí que el amor también puede ser hogar.",
  "Eres la fuerza que aparece cuando más la necesito.",
  "Estoy orgulloso de tu manera de sentir.",
  "Eres la luz que ilumina incluso mis pensamientos más oscuros.",
  "Te quiero porque tu forma de existir me inspira.",
  "Eres la calma que llega cuando más la necesito.",
  "Estoy orgulloso de tu valentía diaria.",
  "Eres la persona que convierte mis días en algo más suave.",
  "Te amo porque contigo todo tiene un brillo distinto.",
  "Eres la fuerza que sostiene mis pasos.",
  "Estoy orgulloso de tu crecimiento constante.",
  "Eres la luz que aparece incluso en mis sombras.",
  "Te quiero porque tu presencia hace que todo sea más fácil.",
  "Eres la calma que me acompaña incluso en silencio.",
  "Estoy orgulloso de tu forma de avanzar sin rendirte.",
  "Eres la persona que transforma mis dudas en claridad.",
  "Te amo porque contigo aprendí a ver la vida de otra manera."
];
